import { Boxes, CircuitBoard, Gauge, Gem, GitBranch, Hammer, Layers3, LayoutDashboard, ListChecks, ListTree, Route, Rows3, Sparkles } from "lucide-react";
import { DockBalancedArchive } from "../archive/dock/DockBalancedArchive";
import { DockEfficiencyArchive } from "../archive/dock/DockEfficiencyArchive";
import { DockFocusArchive } from "../archive/dock/DockFocusArchive";
import { DockShowcaseArchive } from "../archive/dock/DockShowcaseArchive";
import { ArmoryGlassV1 } from "../archive/v1/ArmoryGlassV1";
import { CommandDeckV1 } from "../archive/v1/CommandDeckV1";
import { ForgeWorkbenchV1 } from "../archive/v1/ForgeWorkbenchV1";
import { MiniatureCaseV1 } from "../archive/v1/MiniatureCaseV1";
import { TacticalLedgerV1 } from "../archive/v1/TacticalLedgerV1";
import { ArmoryGlassFutureArchive } from "../archive/v2/ArmoryGlassFutureArchive";
import { BuildTimelineArchive } from "../archive/v2/BuildTimelineArchive";
import { CurvedCommandArchive } from "../archive/v2/CurvedCommandArchive";
import { ForceRibbonArchive } from "../archive/v2/ForceRibbonArchive";
import { GlassLedgerArchive } from "../archive/v2/GlassLedgerArchive";
import type { GalleryConcept } from "./galleryTypes";

export const archiveConcepts: GalleryConcept[] = [
  {
    id: "archive-command-deck",
    mode: "archive",
    name: "Command Deck V1",
    eyebrow: "Archived dark tactical console",
    icon: CircuitBoard,
    bestFor: "Reference for the first dark-console direction.",
    direction: "Dark Material 3 surfaces, teal command rails, restrained neon validation.",
    interaction: "Fast section switching with command-style detail panels and a persistent point ring.",
    tradeoff: "Archived because the V2 set reduces card density and improves flow.",
    component: CommandDeckV1,
  },
  {
    id: "archive-armory-glass",
    mode: "archive",
    name: "Armory Glass V1",
    eyebrow: "Archived first baseline",
    icon: Gem,
    bestFor: "Reference for the original safest product direction.",
    direction: "Light Material 3, frosted trays, soft neumorphic controls, role color accents.",
    interaction: "Equipment tray metaphor with friendly filters and large tap targets.",
    tradeoff: "Superseded by Armory Future.",
    component: ArmoryGlassV1,
  },
  {
    id: "archive-tactical-ledger",
    mode: "archive",
    name: "Tactical Ledger V1",
    eyebrow: "Archived power-user planning sheet",
    icon: Rows3,
    bestFor: "Reference for dense table/list planning.",
    direction: "Dense list/table structure with paper-like depth and sharp information hierarchy.",
    interaction: "Tap rows to inspect, with validation grouped in a bottom drawer.",
    tradeoff: "Superseded by Glass Ledger.",
    component: TacticalLedgerV1,
  },
  {
    id: "archive-miniature-case",
    mode: "archive",
    name: "Miniature Case V1",
    eyebrow: "Archived skeuomorphic case",
    icon: Boxes,
    bestFor: "Reference for tactile collection personality.",
    direction: "Molded compartments, inset model slots, clipped unit cards.",
    interaction: "Roster sections behave like trays with empty slots and selected model cards.",
    tradeoff: "More themed than the V2 refinement direction.",
    component: MiniatureCaseV1,
  },
  {
    id: "archive-forge-workbench",
    mode: "archive",
    name: "Forge Workbench V1",
    eyebrow: "Archived assembly metaphor",
    icon: Hammer,
    bestFor: "Reference for builder/workbench interaction.",
    direction: "Workbench surfaces, raised tools, inset option vise, warm-neutral depth.",
    interaction: "Palette, assembly board, and configuration vise make the build flow explicit.",
    tradeoff: "Superseded by Build Timeline for onboarding clarity.",
    component: ForgeWorkbenchV1,
  },
  {
    id: "archive-armory-future",
    mode: "archive",
    name: "Armory Future V2",
    eyebrow: "Archived V2 baseline",
    icon: Sparkles,
    bestFor: "Reference for the previous light future baseline.",
    direction: "Light frosted Material 3 with a soft shell, force rail, roster surface, and bottom dock.",
    interaction: "Full sample flow from library through export.",
    tradeoff: "Archived after Roster Dock became the chosen inspiration.",
    component: ArmoryGlassFutureArchive,
  },
  {
    id: "archive-curved-command",
    mode: "archive",
    name: "Curved Command V2",
    eyebrow: "Archived V2 rounded shell",
    icon: LayoutDashboard,
    bestFor: "Reference for the rounded dark top-shell direction.",
    direction: "Dark capsule header, curved content panel, pill tabs, and sheet-based configuration.",
    interaction: "Roster, add, and checks are one tap away.",
    tradeoff: "Archived in favor of Dock variants.",
    component: CurvedCommandArchive,
  },
  {
    id: "archive-force-ribbon",
    mode: "archive",
    name: "Force Ribbon V2",
    eyebrow: "Archived V2 organization-first layout",
    icon: ListTree,
    bestFor: "Reference for role-ribbon navigation.",
    direction: "Horizontal role ribbon, continuous lane list, and tonal Material surfaces.",
    interaction: "Selecting a role swaps the roster lane and keeps slot impact visible.",
    tradeoff: "Archived in favor of Dock variants.",
    component: ForceRibbonArchive,
  },
  {
    id: "archive-glass-ledger",
    mode: "archive",
    name: "Glass Ledger V2",
    eyebrow: "Archived V2 power-user table",
    icon: GitBranch,
    bestFor: "Reference for scan-heavy table/list editing.",
    direction: "Frosted table/list hybrid with budget bars and inline status markers.",
    interaction: "Rows expand into detail configuration without card-per-unit browsing.",
    tradeoff: "Archived in favor of Dock variants.",
    component: GlassLedgerArchive,
  },
  {
    id: "archive-build-timeline",
    mode: "archive",
    name: "Build Timeline V2",
    eyebrow: "Archived V2 guided creation flow",
    icon: Route,
    bestFor: "Reference for onboarding and BSData hierarchy.",
    direction: "Stepper rail, one active work surface, soft neumorphic panels.",
    interaction: "System, catalogue, detachment, roster, and validation are explicit steps.",
    tradeoff: "Archived in favor of Dock variants.",
    component: BuildTimelineArchive,
  },
  {
    id: "archive-dock-efficiency",
    mode: "archive",
    name: "Dock Efficiency",
    eyebrow: "Archived dock variant",
    icon: ListChecks,
    bestFor: "Reference for the densest Dock variant.",
    direction: "Restrained dark Material UI, compact rows, minimal decoration.",
    interaction: "Points, checks, section, add, and unit rows stay close together.",
    tradeoff: "Archived after Dock Glass was chosen.",
    component: DockEfficiencyArchive,
  },
  {
    id: "archive-dock-balanced",
    mode: "archive",
    name: "Dock Balanced",
    eyebrow: "Archived dock variant",
    icon: Gauge,
    bestFor: "Reference for the practical default Dock variant.",
    direction: "Dark finance-inspired shell with visible dock labels and comfortable density.",
    interaction: "Original Roster Dock interaction model.",
    tradeoff: "Archived after Dock Glass was chosen.",
    component: DockBalancedArchive,
  },
  {
    id: "archive-dock-focus",
    mode: "archive",
    name: "Dock Focus",
    eyebrow: "Archived dock variant",
    icon: Layers3,
    bestFor: "Reference for lower-cognitive-load Dock editing.",
    direction: "Dark top shell, prominent section rail, quieter rows.",
    interaction: "One active section is emphasized.",
    tradeoff: "Archived after Dock Glass was chosen.",
    component: DockFocusArchive,
  },
  {
    id: "archive-dock-showcase",
    mode: "archive",
    name: "Dock Showcase",
    eyebrow: "Archived dock variant",
    icon: Sparkles,
    bestFor: "Reference for the prettiest Dock presentation.",
    direction: "Large hero points treatment, richer rounded shells, stronger lighting.",
    interaction: "Presentation-oriented Dock flow.",
    tradeoff: "Archived after Dock Glass was chosen.",
    component: DockShowcaseArchive,
  },
];
